import phpFunctions from '@/data/php-functions.json';

import { completionRegistry } from '../registry';
import type { PhpFunction } from '../types';

/**
 * Load native PHP function data into the CompletionRegistry.
 * The data is generated by `npm run generate:php-functions` and committed
 * to git so no network access is required at build time.
 */
export function registerPhpSource(): void {
    completionRegistry.register('php', phpFunctions as unknown as PhpFunction[]);
}
