import wordpressFunctions from '@/data/wordpress-functions.json';

import { completionRegistry } from '../registry';
import type { PhpFunction } from '../types';

/**
 * Load WordPress function data into the CompletionRegistry.
 * The data is generated by `npm run generate:wordpress-functions` and committed
 * to git so no network access is required at build time.
 */
export function registerWordPressSource(): void {
    completionRegistry.register('wordpress', wordpressFunctions as unknown as PhpFunction[]);
}
